<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

	<ItemGroup>
	<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
	<PackageReference Include="Pastel" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Registration.Domain\Registration.Domain.csproj" />
	</ItemGroup>

</Project>
